// Generated by scripts/import-live-seo.mjs from the production site.
export const ADDITIONAL_PAGES = {
  "/blog/best-electrician-services-singapore-2026": {
    "title": "10 Best Electrician Services in Singapore [2026] | Luminous Engineering",
    "description": "Something electrical going wrong at home has a way of feeling urgent even when it isn't dangerous. A socket that sparks when you plug in the kettle, a light…",
    "canonical": "https://luminousengineering.com.sg/blog/best-electrician-services-singapore-2026",
    "bodyClass": "bg-gray-900 text-white",
    "content": "content/pages/blog__best__electrician__services__singapore__2026.html",
    "css": "content/styles/blog__best__electrician__services__singapore__2026.css",
    "source": "https://luminousengineering.com.sg/blog/best-electrician-services-singapore-2026",
    "hasNav": true,
    "hasFooter": true
  },
  "/blog/best-pool-maintenance-companies-singapore-2026": {
    "title": "10 Best Pool Maintenance Companies in Singapore [2026] | Luminous Engineering",
    "description": "A pool in Singapore's climate doesn't stay clean by accident. Between the heat, the humidity, and near-daily rain, algae and cloudy water build up faster here…",
    "canonical": "https://luminousengineering.com.sg/blog/best-pool-maintenance-companies-singapore-2026",
    "bodyClass": "bg-gray-900 text-white",
    "content": "content/pages/blog__best__pool__maintenance__companies__singapore__2026.html",
    "css": "content/styles/blog__best__pool__maintenance__companies__singapore__2026.css",
    "source": "https://luminousengineering.com.sg/blog/best-pool-maintenance-companies-singapore-2026",
    "hasNav": true,
    "hasFooter": true
  },
  "/blog/electrician-price-list-singapore-2026": {
    "title": "Electrician Price List Singapore [2026] | Luminous Engineering",
    "description": "Your ceiling fan is making that clicking sound again. Or half your kitchen sockets just died. Or you've been staring at your DB box wondering if it's finally…",
    "canonical": "https://luminousengineering.com.sg/blog/electrician-price-list-singapore-2026",
    "bodyClass": "bg-gray-900 text-white",
    "content": "content/pages/blog__electrician__price__list__singapore__2026.html",
    "css": "content/styles/blog__electrician__price__list__singapore__2026.css",
    "source": "https://luminousengineering.com.sg/blog/electrician-price-list-singapore-2026",
    "hasNav": true,
    "hasFooter": true
  },
  "/blog/install-power-socket-singapore-price-2026": {
    "title": "Install Power Socket Singapore Price [2026] | Luminous Engineering",
    "description": "Running out of power points is one of the most common complaints in Singapore homes — especially older HDB flats built before everyone owned five charging…",
    "canonical": "https://luminousengineering.com.sg/blog/install-power-socket-singapore-price-2026",
    "bodyClass": "bg-gray-900 text-white",
    "content": "content/pages/blog__install__power__socket__singapore__price__2026.html",
    "css": "content/styles/blog__install__power__socket__singapore__price__2026.css",
    "source": "https://luminousengineering.com.sg/blog/install-power-socket-singapore-price-2026",
    "hasNav": true,
    "hasFooter": true
  },
  "/blog/light-installation-singapore-price-2026": {
    "title": "Light Installation Singapore Price [2026] | Luminous Engineering",
    "description": "New lights can completely change how a room feels — but before you buy that pendant lamp or chandelier, you probably want to know one thing: how much will it…",
    "canonical": "https://luminousengineering.com.sg/blog/light-installation-singapore-price-2026",
    "bodyClass": "bg-gray-900 text-white",
    "content": "content/pages/blog__light__installation__singapore__price__2026.html",
    "css": "content/styles/blog__light__installation__singapore__price__2026.css",
    "source": "https://luminousengineering.com.sg/blog/light-installation-singapore-price-2026",
    "hasNav": true,
    "hasFooter": true
  },
  "/blog/painting-service-singapore-price-list-2026": {
    "title": "Painting Service Singapore PRICE LIST [2026] | Luminous Engineering",
    "description": "You've probably already gotten a few quotes, and they don't match. One painter says $600 for your whole flat. Another says $1,400 for the same job. Neither…",
    "canonical": "https://luminousengineering.com.sg/blog/painting-service-singapore-price-list-2026",
    "bodyClass": "bg-gray-900 text-white",
    "content": "content/pages/blog__painting__service__singapore__price__list__2026.html",
    "css": "content/styles/blog__painting__service__singapore__price__list__2026.css",
    "source": "https://luminousengineering.com.sg/blog/painting-service-singapore-price-list-2026",
    "hasNav": true,
    "hasFooter": true
  },
  "/blog/pool-maintenance-cost-singapore-2026": {
    "title": "Pool Maintenance Cost Singapore [2026] | Luminous Engineering",
    "description": "If you own a pool in Singapore, you already know the weather here doesn't play nice. Rain, heat, and humidity team up to turn a clean pool into a green,…",
    "canonical": "https://luminousengineering.com.sg/blog/pool-maintenance-cost-singapore-2026",
    "bodyClass": "bg-gray-900 text-white",
    "content": "content/pages/blog__pool__maintenance__cost__singapore__2026.html",
    "css": "content/styles/blog__pool__maintenance__cost__singapore__2026.css",
    "source": "https://luminousengineering.com.sg/blog/pool-maintenance-cost-singapore-2026",
    "hasNav": true,
    "hasFooter": true
  },
  "/blog/power-trip-repair-cost-singapore-2026": {
    "title": "Power Trip Repair Cost Singapore [2026] | Luminous Engineering",
    "description": "Your circuit breaker trips, the whole flat goes dark, and you're standing in front of your distribution board wondering whether to reset it or call someone.…",
    "canonical": "https://luminousengineering.com.sg/blog/power-trip-repair-cost-singapore-2026",
    "bodyClass": "bg-gray-900 text-white",
    "content": "content/pages/blog__power__trip__repair__cost__singapore__2026.html",
    "css": "content/styles/blog__power__trip__repair__cost__singapore__2026.css",
    "source": "https://luminousengineering.com.sg/blog/power-trip-repair-cost-singapore-2026",
    "hasNav": true,
    "hasFooter": true
  }
};
