import { cp, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const projectRoot = path.resolve(process.cwd());
const workspaceRoot = path.resolve(projectRoot, "..");
const sourceProjectName = "Luminous_html-2";
const sourceRoot = path.join(workspaceRoot, sourceProjectName);
const contentRoot = path.join(projectRoot, "content");
const publicRoot = path.join(projectRoot, "public");

async function main() {
  await ensureSourceExists();
  await prepareDirectories();
  await copyAssets();
  await generateLegacyCss();
  const pages = await generatePages();
  await writePagesManifest(pages);
  console.log(`Migrated ${Object.keys(pages).length} routes from ${sourceProjectName}.`);
}

async function ensureSourceExists() {
  if (!existsSync(sourceRoot)) {
    throw new Error(`Missing source project: ${sourceRoot}`);
  }
}

async function prepareDirectories() {
  await mkdir(path.join(contentRoot, "pages"), { recursive: true });
  await mkdir(path.join(contentRoot, "shared"), { recursive: true });
  await mkdir(path.join(contentRoot, "styles"), { recursive: true });
  await mkdir(path.join(publicRoot, "images"), { recursive: true });
  await mkdir(path.join(publicRoot, "icons"), { recursive: true });
  await mkdir(path.join(publicRoot, "fonts"), { recursive: true });
}

async function copyAssets() {
  await copyIfExists(path.join(sourceRoot, "assets", "images"), path.join(publicRoot, "images"));
  await copyIfExists(path.join(sourceRoot, "assets", "fonts"), path.join(publicRoot, "fonts"));

  const iconFiles = [
    "favicon.ico",
    "favicon.png",
    "favicon-16x16.png",
    "favicon-32x32.png",
    "apple-touch-icon.png",
    "android-chrome-192x192.png",
    "android-chrome-512x512.png",
    "site.webmanifest"
  ];

  for (const file of iconFiles) {
    await copyIfExists(path.join(sourceRoot, file), path.join(publicRoot, "icons", file));
  }
}

async function copyIfExists(from, to) {
  if (!existsSync(from)) return;
  await cp(from, to, { recursive: true, force: true });
}

async function generateLegacyCss() {
  const css = [
    "/* Generated by scripts/migrate.mjs.",
    "   Page-specific legacy CSS is emitted into content/styles/*.css and injected per route. */",
    "@keyframes floatParticle {",
    "  0%, 100% { transform: translateY(0) translateX(0); }",
    "  25% { transform: translateY(-100px) translateX(50px); }",
    "  50% { transform: translateY(-200px) translateX(-50px); }",
    "  75% { transform: translateY(-100px) translateX(100px); }",
    "}",
    ""
  ].join("\n");

  await writeFile(path.join(projectRoot, "styles", "legacy.css"), css, "utf8");
}

async function generatePages() {
  const htmlFiles = await listFiles(sourceRoot, ".html");
  const pages = {};

  for (const filePath of htmlFiles) {
    const relative = normalizePath(path.relative(sourceRoot, filePath));
    const html = await readFile(filePath, "utf8");
    const bodyMatch = html.match(/<body([^>]*)>([\s\S]*?)<\/body>/i);
    const bodyAttrs = bodyMatch?.[1] || "";
    let body = bodyMatch?.[2] || html;
    const navMatch = body.match(/<nav\b[\s\S]*?<\/nav>/i);
    const footerMatch = body.match(/<footer\b[\s\S]*?<\/footer>/i);
    const hasNav = Boolean(navMatch);
    const hasFooter = Boolean(footerMatch);
    const cssFile = await writePageCss(relative, html);

    body = body
      .replace(/<script\b[\s\S]*?<\/script>/gi, "")
      .replace(/<link\b[^>]*>/gi, "")
      .replace(/<style\b[\s\S]*?<\/style>/gi, "")
      .replace(/<noscript\b[\s\S]*?<\/noscript>/gi, "");

    body = rewriteHtml(body).trim();

    const route = routeFor(relative, pages);
    const aliases = aliasesFor(relative, route);
    const contentFile = `content/pages/${fileId(relative)}.html`;
    await writeFile(path.join(projectRoot, contentFile), body, "utf8");

    const metadata = {
      title: textFromMatch(html.match(/<title>([\s\S]*?)<\/title>/i)),
      description: attrFromMeta(html, "description"),
      canonical: attrFromCanonical(html),
      bodyClass: attrFromBody(bodyAttrs, "class"),
      content: contentFile,
      css: cssFile,
      source: `${sourceProjectName}/${relative}`,
      hasNav,
      hasFooter
    };

    pages[route] = metadata;
    for (const alias of aliases) {
      if (!pages[alias]) {
        pages[alias] = { ...metadata, aliasOf: route };
      }
    }
  }

  return sortObject(pages);
}

async function writePageCss(relative, html) {
  const entries = [];
  const pattern = /<link\b[^>]*href=["']([^"']+\.css[^"']*)["'][^>]*>|<style\b[^>]*>([\s\S]*?)<\/style>/gi;
  let match;

  while ((match = pattern.exec(html))) {
    if (match[1]) {
      const href = match[1].replace(/\?.*$/, "");
      const cssPath = resolveCssPath(href);
      if (cssPath && existsSync(cssPath)) {
        const css = await readFile(cssPath, "utf8");
        entries.push(`/* ${href} */\n${rewriteAssetPaths(css)}`);
      }
    } else if (match[2]) {
      entries.push(`/* inline style from ${relative} */\n${rewriteAssetPaths(match[2])}`);
    }
  }

  const content = [
    `/* Generated per-page CSS for ${sourceProjectName}/${relative}. */`,
    "@keyframes floatParticle {",
    "  0%, 100% { transform: translateY(0) translateX(0); }",
    "  25% { transform: translateY(-100px) translateX(50px); }",
    "  50% { transform: translateY(-200px) translateX(-50px); }",
    "  75% { transform: translateY(-100px) translateX(100px); }",
    "}",
    ...entries
  ].join("\n\n");

  const cssFile = `content/styles/${fileId(relative)}.css`;
  await writeFile(path.join(projectRoot, cssFile), content, "utf8");
  return cssFile;
}

function resolveCssPath(href) {
  if (/^https?:\/\//i.test(href)) return null;
  const normalized = href.startsWith("/") ? href.slice(1) : href;
  return path.join(sourceRoot, normalized);
}

async function writePagesManifest(pages) {
  const js = `export const PAGES = ${JSON.stringify(pages, null, 2)};\n\n` +
    `export function getPageByRoute(route) {\n  return PAGES[route] || null;\n}\n\n` +
    `export function getStaticSlugs() {\n  return Object.keys(PAGES).map((route) => ({\n    slug: route === "/" ? [] : route.slice(1).split("/")\n  }));\n}\n`;

  await writeFile(path.join(projectRoot, "lib", "pages.js"), js, "utf8");
}

async function listFiles(directory, extension) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...await listFiles(fullPath, extension));
    } else if (entry.isFile() && entry.name.endsWith(extension)) {
      files.push(fullPath);
    }
  }

  return files.sort();
}

function routeFor(relative, existingPages) {
  let route;
  if (relative === "index.html") {
    route = "/";
  } else if (relative === "services.html") {
    route = "/services.html";
  } else if (relative === "404.html") {
    route = "/404";
  } else if (relative.endsWith("/index.html")) {
    route = `/${relative.slice(0, -"/index.html".length)}`;
  } else {
    route = `/${relative.slice(0, -".html".length)}`;
  }

  if (existingPages[route]) {
    return `/${relative}`;
  }

  return route;
}

function aliasesFor(relative, route) {
  const aliases = new Set();
  if (relative.endsWith(".html")) {
    aliases.add(`/${relative}`);
  }
  if (relative === "index.html") aliases.add("/index.html");
  if (relative === "404.html") aliases.add("/not-found");
  aliases.delete(route);
  return [...aliases];
}

function rewriteHtml(input) {
  return rewriteAssetPaths(input)
    .replace(/\s(?:src|href)=["']\/assets\/css\/[^"']+["']/gi, "")
    .replace(/\s(?:src|href)=["']\/assets\/js\/[^"']+["']/gi, "")
    .replace(/href=["']([^"']+)\.html["']/gi, (match, href) => {
      if (/^(https?:|mailto:|tel:|#)/i.test(href)) return match;
      return `href="${href}"`;
    });
}

function rewriteAssetPaths(input) {
  return input
    .replace(/\/assets\/images\//g, "/images/")
    .replace(/\/assets\/icons\//g, "/icons/")
    .replace(/\/assets\/fonts\//g, "/fonts/")
    .replace(/(["'(])assets\/images\//g, "$1/images/")
    .replace(/(["'(])assets\/fonts\//g, "$1/fonts/")
    .replace(/(["'(])\.\.\/images\//g, "$1/images/")
    .replace(/(["'(])\.\.\/fonts\//g, "$1/fonts/")
    .replace(/\\\\:/g, "\\:");
}

function fileId(relative) {
  return relative.replace(/\.html$/i, "").replace(/[^a-z0-9]+/gi, "__").replace(/^__|__$/g, "") || "home";
}

function textFromMatch(match) {
  return decodeEntities((match?.[1] || "").replace(/\s+/g, " ").trim());
}

function attrFromMeta(html, name) {
  const match = html.match(new RegExp(`<meta[^>]+name=["']${name}["'][^>]+content=["']([^"']*)["']`, "i"));
  return decodeEntities(match?.[1] || "");
}

function attrFromCanonical(html) {
  const match = html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']*)["']/i);
  return decodeEntities(match?.[1] || "");
}

function attrFromBody(attrs, name) {
  const match = attrs.match(new RegExp(`${name}=["']([^"']*)["']`, "i"));
  return match?.[1] || "";
}

function decodeEntities(value) {
  return value
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#039;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

function normalizePath(value) {
  return value.split(path.sep).join("/");
}

function sortObject(object) {
  return Object.fromEntries(Object.entries(object).sort(([a], [b]) => a.localeCompare(b)));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
